[package]
name = "Paxy"
version = "0.1.0"
authors = ["TheMode <themode@outlook.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.5.0", features = ["full"] }
bytes = "1.0.1"
